Repository levxyca/diciotech, pull requests merged in 2023-10, with the labels that each got.

#60 new: adição do termo bug
  assets/data/cards_pt-br.json
Labels: documentation

#61 feat: pontuação dos termos e algumas tags ajustadas
  assets/data/cards_pt-br.json
Labels: enhancement

#45 Adicionando novo termo: compilador
  assets/data/cards_pt-br.json
Labels: documentation

#51 feat: "react native e mobile first"
  assets/data/cards_pt-br.json
Labels: documentation

#52 feat: Adding maximum width to last card.
  assets/css/style.css
Labels: enhancement

#68 new: adição do termo python
  assets/data/cards_pt-br.json
Labels: documentation

#72 fix: quebra de linha de elementos <code>
  assets/css/style.css
  assets/css/style.css.map
  assets/data/cards_pt-br.json
  assets/sass/style.sass
  index.html
Labels: bug, wontfix

#58 new-term: Abstração
  assets/data/cards_pt-br.json
Labels: documentation

#76 Fix: Site sem funcionar em produção
  assets/data/cards_pt-br.json
  assets/js/script.js
Labels: bug

#63 feat: adicionando os termos orm, sql e node.js
  assets/data/cards_pt-br.json
Labels: documentation

#74 feat: adding GNU General public license v3
  LICENSE
Labels: documentation

#67 feat: Adicionei termos relacionados a programação baixo nivel e linguagens do tipo
  assets/data/cards_pt-br.json
Labels: documentation

#71 docs(CONTRIBUTING): atualiza a documentação de contribuição para atender tags
  CONTRIBUTING.md
Labels: documentation

#79 refactor: dark mode
  assets/css/dark_mode.css
  assets/css/dark_mode.css.map
  assets/css/style.css
  assets/css/style.css.map
  assets/data/cards_pt-br.json
  assets/js/dark_mode.js
  assets/sass/_variables.sass
  assets/sass/dark_mode.sass
  assets/sass/style.sass
Labels: enhancement

#85 Novo termo 'cache'
  assets/data/cards_pt-br.json
Labels: documentation

#90 Add React, componentes e propriedades
  assets/data/cards_pt-br.json
Labels: documentation

#97 fix: ajuste na tag duplicada
  assets/data/cards_pt-br.json
Labels: bug, documentation

#103 adicionando novos termos técnicos ao diciotech
  assets/data/cards_pt-br.json
Labels: documentation

#107 Remove duplicate Mobile First term and rewrite him
  assets/data/cards_pt-br.json
Labels: bug, documentation

#105 docs: Mudança do screenshot do README.md
  assets/css/style.css
  assets/css/style.css.map
  assets/img/diciotech-screenshot.png
  assets/img/no-results-found.png
  assets/js/script.js
  assets/sass/style.sass
Labels: documentation

#111 docs: adicionado seção para tags, na documentação
  CONTRIBUTING.md
  README.md
Labels: documentation
