Repository levxyca/diciotech, pull requests merged in 2024-05, with the labels that each got.

#136 fix: adiciona uma função de hash para gerar o id do card
  assets/data/cards_pt-br.json
  assets/js/script.js
Labels: bug

#162 feat: Conceito de coalescência nula
  assets/data/cards_pt-br.json
Labels: enhancement

#161 Adicionando Scrum e UML
  assets/data/cards_pt-br.json
Labels: enhancement

#166 feat: adiciona cards de swift, swiftui e uikit
  assets/data/cards_pt-br.json
Labels: new technical term
