Repository levxyca/diciotech, pull requests merged in 2024-06, with the labels that each got.

#168 feat: adicionando conceito, code smells
  assets/data/cards_pt-br.json
Labels: new technical term

#169 Adiciona templates de repositório (#92)
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/inclusao-de-termo.md
Labels: enhancement

#98 Adicionando termos técnicos sobre versionamento
  assets/data/cards_pt-br.json
Labels: documentation

#115 feat: Adiciona termos técnicos de DOM, Responsividade e SASS/SCSS
  assets/data/cards_pt-br.json
Labels: documentation

#119 Update cards_pt-br.json with some git and versioning terms.
  assets/data/cards_pt-br.json
Labels: documentation

#125 Remove duplication term.
  assets/data/cards_pt-br.json
Labels: bug, documentation

#134 adicionando termos: computação em nuvem, CORS e garbage collector
  assets/data/cards_pt-br.json
Labels: documentation
