Repository levxyca/diciotech, pull requests merged in 2024-07, with the labels that each got.

#150 Adicionadas definições referentes a área de IA #146
  CONTRIBUTING.md
  assets/data/cards_pt-br.json
Labels: new technical term

#177 Cria modelo de PR para o projeto
  .github/pull_request_template.md
Labels: documentation, enhancement

#154 fix: fix issue (#153)
  assets/css/cookies.css
  assets/sass/cookies.sass
Labels: bug
