Repository levxyca/diciotech, pull requests merged in 2024-10, with the labels that each got.

#198 Pre commit hooks
  .pre-commit-config.yaml
  assets/data/cards_pt-br.json
  format_data.py
  run_on_data_changed.sh
Labels: enhancement

#211 Realizando alterações na documentação
  CONTRIBUTING.md
Labels: documentation

#202 Adicionados termos de Design
  assets/data/cards_pt-br.json
Labels: new technical term

#209 Adicionado o termo RPA
  assets/data/cards_pt-br.json
Labels: new technical term

#212 Remove termo duplicado "ORM"
  assets/data/cards_pt-br.json
Labels: bug

#205 Adiciona os conceitos de frameworks frontend populares, como: Angular.js, Vue.js, Svelte e Next.js
  assets/data/cards_pt-br.json
Labels: new technical term

#203 Adicionados termos MLOps, DevOps, CI e CD
  assets/data/cards_pt-br.json
Labels: new technical term

#218 Ajuste do icone de favorito
  assets/css/dark_mode.css
  assets/css/style.css
  assets/js/script.js
Labels: bug

#221 Ajeitado comando sass, tags existentes
  CONTRIBUTING.md
Labels: bug, documentation

#219 Pega tema do sistema do usuário, remove piscada quando tema escuro
  assets/css/cookies.css
  assets/css/cookies.css.map
  assets/css/dark_mode.css
  assets/css/dark_mode.css.map
  assets/css/style.css
  assets/css/style.css.map
  assets/js/dark_mode.js
  assets/js/script.js
  assets/js/theme.js
  assets/sass/_variables.sass
  assets/sass/cookies.sass
  assets/sass/dark_mode.sass
  assets/sass/dark_theme.sass
  assets/sass/light_theme.sass
  assets/sass/style.sass
  index.html
Labels: bug, enhancement

#215 Adicionado o termo CMD
  assets/data/cards_pt-br.json
Labels: new technical term

#241 Ajusta as Tags dos termos Scrum e UML
  assets/data/cards_pt-br.json
Labels: bug, help wanted

#210 Novos termos
  assets/data/cards_pt-br.json
Labels: new technical term

#223 Adicionado contador com total de termos
  assets/js/script.js
  index.html
Labels: enhancement

#225 Valida json somente se um json foi modificado
  .github/workflows/json-yaml-validate.yml
Labels: enhancement
