Repository levxyca/diciotech, pull requests merged in 2024-09, with the labels that each got.

#179 Fix duplicatas
  assets/data/cards_pt-br.json
Labels: bug

#189 GitHub Action personalizada para verificar issue no PR
  .github/workflows/issue-check.yml
Labels: enhancement

#191 Adicionado workflow pra validar o json com os dados
  .github/workflows/json-yaml-validate.yml
Labels: enhancement

#151 Adicionados os termos tag, loop e xml
  assets/data/cards_pt-br.json
Labels: new technical term

#187 Feat: adição dos termos DOS, DDOS, BOTNET's
  assets/data/cards_pt-br.json
Labels: new technical term

#194 Update Dark mode
  assets/css/dark_mode.css
  assets/css/dark_mode.css.map
  assets/sass/_variables.sass
  assets/sass/dark_mode.sass
  index.html
Labels: enhancement
