Repository levxyca/diciotech, pull requests merged in 2024-11, with the labels that each got.

#253 Garante que a descrição termina com um ponto final
  format_data.py
Labels: enhancement

#251 Mudando a screenshot do projeto por uma com múltiplos dispositivos
  assets/img/diciotech-screenshot.png
Labels: enhancement

#247 Criado workflow pra ordenar os arquivos com as palavras
  .github/workflows/sort-data.yml
Labels: bug

#240 Adicionado formatador Prettier
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/inclusao-de-termo.md
  .github/workflows/issue-check.yml
  .github/workflows/prettier.yml
  .gitignore
  .pre-commit-config.yaml
  .prettierignore
  CONTRIBUTING.md
  README.md
  ROADMAP.md
  assets/css/style.css
  assets/data/cards_pt-br.json
  assets/js/cookies.js
  assets/js/levenshtein.js
  assets/js/script.js
  assets/js/theme.js
  assets/sass/_variables.sass
  assets/sass/cookies.sass
  assets/sass/dark_theme.sass
  assets/sass/light_theme.sass
  assets/sass/style.sass
  assets/scss/_variables.scss
  assets/scss/cookies.scss
  assets/scss/dark_theme.scss
  assets/scss/light_theme.scss
  assets/scss/style.scss
  index.html
  package-lock.json
  package.json
  run_on_code_changed.sh
Labels: enhancement

#262 Permite instalação como um Progressive Web App
  assets/js/script.js
  diciotech.webmanifest
  index.html
Labels: enhancement

#263 Resolvido bug ao ordenar arquivos com dados
  .github/workflows/sort-data.yml
Labels: bug

#255 feat: simplicando termos de linguagens
  assets/data/cards_pt-br.json
Labels: bug

#248 Implementando exemplo de recursão
  assets/css/style.css.map
  assets/data/cards_pt-br.json
Labels: new technical term
